name: ok_book
description: Premium Ledger App Clone

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  google_fonts: ^6.1.0
  intl: ^0.18.1
  flutter_animate: ^4.2.0

flutter:
  uses-material-design: true
