import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'app_state.dart';
import 'party_screen.dart';
import 'transaction_screen.dart';
import 'reports_screen.dart';
import 'more_screen.dart';
class DashboardScreen extends StatefulWidget{const DashboardScreen({super.key});@override State<DashboardScreen> createState()=>_S();}
class _S extends State<DashboardScreen>{int tab=0;final pages=const[HomeView(),PartyScreen(),TransactionScreen(),ReportsScreen(),MoreScreen()];@override Widget build(BuildContext c)=>Scaffold(body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(x)=>setState(()=>tab=x),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.people_outline),selectedIcon:Icon(Icons.people),label:'Khata'),NavigationDestination(icon:Icon(Icons.receipt_long_outlined),selectedIcon:Icon(Icons.receipt_long),label:'Transactions'),NavigationDestination(icon:Icon(Icons.bar_chart_outlined),selectedIcon:Icon(Icons.bar_chart),label:'Reports'),NavigationDestination(icon:Icon(Icons.more_horiz),label:'More')]));}
class HomeView extends StatelessWidget{const HomeView({super.key});String money(int n)=>'₹${(n/100).toStringAsFixed(2)}';@override Widget build(BuildContext c){final s=c.watch<AppState>();return SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[Text('Dashboard',style:Theme.of(c).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:4),Text('Everything important at a glance'),const SizedBox(height:18),GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),children:[Metric('You will get',money(s.receivable),Icons.arrow_downward),Metric('You will give',money(s.payable),Icons.arrow_upward),Metric('Today received',money(s.todayReceived),Icons.payments),Metric('Today given',money(s.todayGiven),Icons.credit_score)]),const SizedBox(height:10),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Quick actions',style:TextStyle(fontWeight:FontWeight.bold,fontSize:18)),const SizedBox(height:12),Wrap(spacing:10,runSpacing:10,children:[Action('Give',Icons.arrow_upward,()=>_party(c,'give')),Action('Receive',Icons.arrow_downward,()=>_party(c,'receive')),Action('Customer',Icons.person_add,()=>_add(c,'customer')),Action('Supplier',Icons.local_shipping,()=>_add(c,'supplier')),Action('Expense',Icons.money_off,()=>_expense(c))])])))]));}
void _party(BuildContext c,String type){Navigator.push(c,MaterialPageRoute(builder:(_)=>PartyScreen(initialAction:type)));}
void _add(BuildContext c,String type){showDialog(context:c,builder:(_)=>PartyDialog(type:type));}
void _expense(BuildContext c){showDialog(context:c,builder:(_)=>ExpenseDialog());}}
class Metric extends StatelessWidget{final String t,v;final IconData i;const Metric(this.t,this.v,this.i,{super.key});@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:Theme.of(c).colorScheme.primary),const Spacer(),Text(t),Text(v,style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold))])));}
class Action extends StatelessWidget{final String t;final IconData i;final VoidCallback f;const Action(this.t,this.i,this.f,{super.key});@override Widget build(BuildContext c)=>FilledButton.tonalIcon(onPressed:f,icon:Icon(i),label:Text(t));}
class PartyDialog extends StatefulWidget{final String type;const PartyDialog({required this.type,super.key});@override State<PartyDialog> createState()=>_PD();}
class _PD extends State<PartyDialog>{final n=TextEditingController(),p=TextEditingController();@override Widget build(BuildContext c)=>AlertDialog(title:Text('Add ${widget.type}'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Name')),TextField(controller:p,decoration:const InputDecoration(labelText:'Phone'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:()async{await c.read<AppState>().addParty(name:n.text.trim(),phone:p.text.trim(),type:widget.type);if(c.mounted)Navigator.pop(c);},child:const Text('Save'))]);}}
class ExpenseDialog extends StatefulWidget{const ExpenseDialog({super.key});@override State<ExpenseDialog> createState()=>_ED();}
class _ED extends State<ExpenseDialog>{final a=TextEditingController();@override Widget build(BuildContext c)=>AlertDialog(title:const Text('Add expense'),content:TextField(controller:a,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Amount (₹)')),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:()async{final x=int.tryParse(a.text)??0;await c.read<AppState>().addExpense(amount:x*100,category:'Other');if(c.mounted)Navigator.pop(c);},child:const Text('Save'))]);}}
