import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'app_state.dart';
import 'models.dart';
class PartyScreen extends StatelessWidget{final String? initialAction;const PartyScreen({super.key,this.initialAction});@override Widget build(BuildContext c){final s=c.watch<AppState>();final all=[...s.customers,...s.suppliers];return Scaffold(appBar:AppBar(title:const Text('Khata'),actions:[IconButton(onPressed:()=>showDialog(context:c,builder:(_)=>PartyDialog2(type:'customer')),icon:const Icon(Icons.add))]),body:all.isEmpty?const Center(child:Text('No parties yet. Tap + to add one.')):ListView.builder(itemCount:all.length,itemBuilder:(_,i){final p=all[i];final b=s.balance(p);return Card(child:ListTile(leading:CircleAvatar(child:Text(p.name.isEmpty?'?':p.name[0].toUpperCase())),title:Text(p.name),subtitle:Text('${p.type} • ${p.phone}'),trailing:Text('₹${(b.abs()/100).toStringAsFixed(2)}',style:TextStyle(fontWeight:FontWeight.bold,color:b>0?Colors.red:Colors.green)),onTap:()=>showDialog(context:c,builder:(_)=>PartyDetail(party:p)));}));}}
class PartyDialog2 extends StatefulWidget{final String type;const PartyDialog2({required this.type,super.key});@override State<PartyDialog2> createState()=>_S();}
class _S extends State<PartyDialog2>{final n=TextEditingController(),p=TextEditingController();String type='customer';@override void initState(){super.initState();type=widget.type;}@override Widget build(BuildContext c)=>AlertDialog(title:const Text('Add party'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(value:type,items:const[DropdownMenuItem(value:'customer',child:Text('Customer')),DropdownMenuItem(value:'supplier',child:Text('Supplier'))],onChanged:(v)=>setState(()=>type=v!),decoration:const InputDecoration(labelText:'Type')),TextField(controller:n,decoration:const InputDecoration(labelText:'Name')),TextField(controller:p,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Phone'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:()async{if(n.text.trim().isEmpty)return;await c.read<AppState>().addParty(name:n.text.trim(),phone:p.text.trim(),type:type);if(c.mounted)Navigator.pop(c);},child:const Text('Save'))]);}}
class PartyDetail extends StatelessWidget{final Party party;const PartyDetail({required this.party,super.key});@override Widget build(BuildContext c){final s=c.watch<AppState>();final b=s.balance(party);return AlertDialog(title:Text(party.name),content:Column(mainAxisSize:MainAxisSize.min,children:[Text('Balance',style:Theme.of(c).textTheme.titleMedium),Text('₹${(b.abs()/100).toStringAsFixed(2)}',style:const TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:16),Row(children:[Expanded(child:FilledButton(onPressed:()=>_tx(c,'give'),child:const Text('Give'))),const SizedBox(width:8),Expanded(child:FilledButton.tonal(onPressed:()=>_tx(c,'receive'),child:const Text('Receive')))])]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Close'))]);}
void _tx(BuildContext c,String type){Navigator.pop(c);showDialog(context:c,builder:(_)=>TransactionDialog(party:party,type:type));}}
class TransactionDialog extends StatefulWidget{final Party party;final String type;const TransactionDialog({required this.party,required this.type,super.key});@override State<TransactionDialog> createState()=>_T();}
class _T extends State<TransactionDialog>{final a=TextEditingController(),d=TextEditingController();@override Widget build(BuildContext c)=>AlertDialog(title:Text(widget.type=='give'?'Give credit':'Receive payment'),content:Column(mainAxisSize:MainAxisSize.min,children:[Text('For ${widget.party.name}'),TextField(controller:a,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Amount (₹)')),TextField(controller:d,decoration:const InputDecoration(labelText:'Description'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:()async{final x=int.tryParse(a.text)??0;if(x<=0)return;await c.read<AppState>().addTxn(party:widget.party,amount:x*100,type:widget.type,description:d.text);if(c.mounted)Navigator.pop(c);},child:const Text('Save'))]);}}
